Add parallel and regenerate to Gitlab pipelines

diff --git a/project-base/.gitlab-ci.yml b/project-base/.gitlab-ci.yml
--- a/project-base/.gitlab-ci.yml
+++ b/project-base/.gitlab-ci.yml
@@ -119,6 +119,15 @@ test:storefront-acceptance:
     <<: *only-default
     tags:
         - tests
+#    parallel:
+#        matrix:
+#            -   GROUP: "authentication"
+#            -   GROUP: "cart"
+#            -   GROUP: "order"
+#            -   GROUP: "transportAndPayment"
+#            -   GROUP: "visits"
+#            -   GROUP: "others"
+
     artifacts:
         paths:
             - ./storefront/cypress/videos/
@@ -134,12 +143,65 @@ test:storefront-acceptance:
         - docker compose up -d
         - docker compose exec -T php-fpm php phing -D production.confirm.action=y composer-prod db-create frontend-api-generate-new-keys build-demo-dev-quick error-pages-generate
         - cd storefront
-        - docker compose run cypress
+        - GROUP=$GROUP docker compose run cypress
     after_script:
         - docker compose logs php-fpm > php-fpm-log.txt
         - docker compose logs webserver > webserver-log.txt
         - docker compose logs storefront > storefront-log.txt
     interruptible: true
+
+regenerate-storefront-screenshots:
+    image: tmaier/docker-compose:latest
+    stage: regenerate
+    <<: *only-default
+    tags:
+        - tests
+    needs:
+        - build
+        - build-storefront
+    #    parallel:
+    #        matrix:
+    #            - GROUP: "authentication"
+    #            - GROUP: "cart"
+    #            - GROUP: "order"
+    #            - GROUP: "transportAndPayment"
+    #            - GROUP: "visits"
+    #            - GROUP: "others"
+    artifacts:
+        paths:
+            - ./storefront/cypress/snapshots/
+            - php-fpm-log.txt
+            - webserver-log.txt
+            - storefront-log.txt
+        when: on_failure
+        expire_in: 1 day
+    script:
+        - apk add --no-cache git
+        - git config --global user.name "Shopsys Bot"
+        - git config --global user.email "bot@shopsys.com"
+        - git clean -fdx
+        - git checkout "$CI_COMMIT_REF_NAME"
+        - cp -f ./gitlab/docker-compose-ci.yml ./docker-compose.yml
+        - docker compose up -d
+        - docker compose exec -T php-fpm php phing -D production.confirm.action=y composer-prod db-create frontend-api-generate-new-keys build-demo-dev-quick error-pages-generate
+        - GROUP=$GROUP docker compose run cypress-regenerate-screenshots
+        - git add ./storefront/cypress/snapshots/e2e
+        - git status
+        - |
+            if ! git diff --staged --quiet; then
+                git commit -m "Regenerated Cypress screenshots for ${GROUP} group"
+                git fetch origin "$CI_COMMIT_REF_NAME"
+                git pull --rebase origin "$CI_COMMIT_REF_NAME"
+                git push https://shopsys_bot:$API_TOKEN@gitlab.shopsys.cz/ss6-projects/project-base.git "$CI_COMMIT_REF_NAME" --force -v || (echo "Failed to push changes" && git log -n 5 && exit 1)
+            else
+                echo "No changes in snapshots, skipping commit."
+            fi
+    after_script:
+        - docker compose logs php-fpm > php-fpm-log.txt
+        - docker compose logs webserver > webserver-log.txt
+        - docker compose logs storefront > storefront-log.txt
+    interruptible: true
+    when: manual
 
 review:
     stage: review
